services:
  leafy-bank-backend-openfinance:
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile.backend
    image: leafy-bank-backend-openfinance-image:latest
    ports:
      - "8000:8000"
    restart: always
    container_name: leafy-bank-backend-openfinance-container